### ISSUE TITLE
`null` handling in `if ... then ... else` expressions

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Trevas-JS#117]
We witnessed a curious behavior when handling `null` variables in `if ... then ... else` expressions.

# How to reproduce

Consider this expressions results when the variable `VAR` has a `null` value.

```vtl
if isnull(VAR)
then "A" 
else if  VAR = "2"
    then "B" 
    else if  VAR = "1" 
        then "C" 
        else "D"
```

...returns "A" whereas...

```vtl
if  VAR = "1" 
then "C" 
else if  VAR = "2" 
    then "B" 
    else if isnull(VAR) 
        then "A" 
        else "D"
```

...returns `null`.

This can be reproduced in the[ Trevas storybook](https://inseefr.github.io/Trevas-JS/storybook/?path=/story/interpretor--default) with this binding:

```json
{"VAR": null}
```

**Comment by NicoLaval** [comment]
According to VTL specification, it's a Trevas JS bug: 

`The if operator returns thenOperand if condition evaluates to true, elseOperand otherwise`

I will fix.

Nevertheless, I think it's not right. When you proceed to 

```
if  VAR = "1" 
then "C" 
else if  VAR = "2" 
    then "B" 
    else if isnull(VAR) 
        then "A" 
        else "D"
```

The first solved operation is `VAR = "1"`, returning `null` when VAR = null (equal statement can be true, can be false, due to indecision, so the result is null). Applying the same reasoning, `if null then "C" else ...` can return thenOperand or elseOperand so the result would be `null`.
