### ISSUE TITLE
Rule groups

### ISSUE THREAD

**Issue by hadrienk** [InseeFr/Trevas-JS#38]
New rules make implementation difficult; arithmetic and concatenation operators are now in `arithmeticExprOrConcat`. And arithmetic and boolean are mixed in `unaryExpr`.

This mix of category (arithmetic, string, boolean) and kind of operator (binary, unary) is challenging when implementing Visitors with a clear separation of concerns.

**Comment by vignola** [comment]
Before they were separated it is true, now they have been grouped because the precedence of operators dictates that they are at the same level. In the previous version, the precedence established by the specifications was broken. 
It must be said that they are operators working on different domains but given the implicit cast it is virtually possible to use them together.

**Comment by hadrienk** [comment]
What what the precedence issue? We had to fix an issue with `-`. There was a bug/typo in the grammar. See https://github.com/InseeFr/VTL-Tools/commit/e1174d2c2103d172deaa0f1c8638fb166fb44b0a

**Comment by vignola** [comment]
The precedence order specified in paragraph VTL-ML - Evaluation order of the Operators of the reference manual were not respected for all the operators in the previous grammar

yes it depends on the choice you did at the beginning to group operators maybe there are different alternatives

**Comment by FranckCo** [comment]
Moved to https://github.com/VTL-Community/VTL-Community/issues/15.
