### ISSUE TITLE
Propose interface for datasets

### ISSUE THREAD

**Issue by FranckCo** [InseeFr/Trevas-JS#47]
In order to expand the support of dataset, we need an abstract definition of the dataset type.

**Comment by romaintailhurat** [comment]
Working on it: https://github.com/InseeFr/VTL-Tools/pull/49

**Comment by romaintailhurat** [comment]
Because we don't have abstraction like [Typescript interface](https://www.typescriptlang.org/docs/handbook/interfaces.html), it's hard to reify our intended "outer" dataset representation.

What would be the best way to document and represent it in the code ?

Our current proposition is an object of this shape:

```javascript
{
  "ds": {
    // Holds the dataset structure information
    "dataStructure": {
      "col_1": {
        "name": "col_1",
        "role": "MEASURE"
      }
    },
    // Holds the columns, named and store as arrays
    "dataPoints": {
      "col_1": [
        1,
        2,
        3
      ]
    }
  }
}
```
